import Config

# Local SQLite file. Kept under priv so it travels with the project
# tree, gitignored (added below). Production points at a mounted
# volume via runtime.exs.
config :aviary, Aviary.Repo,
  database: Path.expand("../priv/aviary_dev.db", __DIR__),
  pool_size: 5,
  show_sensitive_data_on_connection_error: true

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :aviary, AviaryWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "gfPGBD0yjJJqiwx1pEwiXn6/ACvFKipifNNRjOO84Vmz5HkLrqmK/JZSyk7ZYxst",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:aviary, ~w(--sourcemap=inline --watch)]},
    # Tailwind v4's standalone binary probes for watchman as its
    # preferred file watcher and emits `sh: line 1: watchman: command
    # not found` to stderr once per build when it isn't installed.
    # Its bundled parcel-watcher fallback then runs and builds finish
    # normally — the line is purely cosmetic, but it lands in the dev
    # log on every reload and drowns out real errors over time.
    #
    # We can't install watchman to silence it the "right" way on
    # aarch64: watchman-bin in AUR ships an x86_64 binary, and the
    # source PKGBUILD's dep `fizz` is missing from AUR entirely. So we
    # wrap the mix task in bash and filter that one stderr line. When
    # the watchman-on-aarch64 situation is resolved (or Tailwind stops
    # auto-probing for it), revert to the upstream form:
    #
    #   tailwind: {Tailwind, :install_and_run, [:aviary, ~w(--watch)]}
    bash: ["-c", "mix tailwind aviary --watch 2>&1 | grep --line-buffered -v 'watchman: command not found'"]
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :aviary, AviaryWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/aviary_web/router\.ex$"E,
      ~r"lib/aviary_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable dev routes for dashboard and mailbox
config :aviary, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true
