import Config

# Note we also include the path to a cache manifest
# containing the digested version of static files. This
# manifest is generated by the `mix assets.deploy` task,
# which you should run after static files are built and
# before starting your production server.
config :aviary, AviaryWeb.Endpoint, cache_static_manifest: "priv/static/cache_manifest.json"

# Force using SSL in production. This also sets the "strict-security-transport" header,
# known as HSTS. If you have a health check endpoint, you may want to exclude it below.
# Note `:force_ssl` is required to be set at compile-time.
config :aviary, AviaryWeb.Endpoint,
  force_ssl: [
    rewrite_on: [:x_forwarded_proto],
    exclude: [
      # paths: ["/health"],
      # Sonarr posts to /api/sonarr/webhook over the docker bridge as
      # plain HTTP with a `host.docker.internal` Host header. Without
      # the exclusion, Plug.SSL 307s it to PHX_HOST and the webhook
      # never reaches the router — Reconcile stops running and blocked
      # imports sit forever. Silent when it breaks; drop with care.
      hosts: ["localhost", "127.0.0.1", "host.docker.internal"]
    ]
  ]

# Do not print debug messages in production
config :logger, level: :info

# Runtime production configuration, including reading
# of environment variables, is done on config/runtime.exs.
